apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: haproxy
  namespace: jduimovich
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: graphtuitous
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: haproxy
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: haproxy-
      labels:
        build.appstudio.openshift.io/application: graphtuitous
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: haproxy
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: jduimovich
    spec:
      params:
      - name: git-url
        value: https://github.com/jduimovich/graphtuitous
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:jduimovich-haproxy-$(tt.params.git-revision)
      - name: dockerfile
        value: services/haproxy/Dockerfile
      - name: path-context
        value: services/haproxy
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:0b05a990917f20f82394d02f28841500df23e612
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: haproxy/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
